/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.movista.newrelic;


import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import com.newrelic.agent.android.NewRelic;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="Newrelicandroid", id="com.movista.newrelic")
public class NewrelicandroidModule extends KrollModule
{

	private static String NewRelicID = "YourTokenHere";

	public NewrelicandroidModule()
	{
		super();
	}

	@Kroll.method
	public void start(String token)
	{
		NewRelicID = token;
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.e(NewRelicID,NewRelicID);
		// put module init code that needs to run when the application is created
		NewRelic.withApplicationToken(NewRelicID).start(app.getApplicationContext());
	}


}
